

##  instanceof

verifica se algo Ã© intancia  de  outra


try(){}
catch(err){

}
finally()


